/*****************************************************************************
 * Copyright (c) 2011 Atos Origin.
 *
 *    
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *  Anne Haugommard (Atos Origin) anne.haugommard@atosorigin.com - Initial API and implementation
 *
 *****************************************************************************/
package org.eclipse.gendoc.wizard;

import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * the loader of the template for document generation. to use it, put an extension to
 * :"org.eclipse.gendoc.wizard.runner", and reference your own IGendocRunner
 * @see IGendocSelectionConverterRunner
 */
public interface IGendocRunner
{

    /**
     * @return give all the possible extension of model to treat
     */
    Pattern getPattern();
    

    /**
     * @return all format of document possible to be generated by this runner
     */
    List<IGendocTemplate> getGendocTemplates();

    /**
     * @return the label associated to this runner. use for display
     */
    String getLabel();
    
    Map<String, String> getAdditionnalParameters();
}
