/*****************************************************************************
 * Copyright (c) 2011 Atos Origin.
 *
 *    
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *  Anne Haugommard (Atos Origin) anne.haugommard@atosorigin.com - Initial API and implementation
 *
 *****************************************************************************/
package org.eclipse.gendoc.wizard;

import java.net.URL;

/**
 * represent the type of format that can be generated by a template type to use it, create a list of it in a runner
 */
public interface IGendocTemplate
{

    /**
     * @return the out put extension of the format of document to generate
     */
    String getOutPutExtension();

    /**
     * 
     * @return the access path URI to specify where is the file containing acceleo script for generation
     */
    URL getTemplate();

    /**
     * @return the generic model key associated to the future model
     */
    String getModelKey();

    /**
     * @return the generic key to use in order to specify output repository
     */
    String getOutputKey();

    /**
     * @return give description associated to the kind of document generation user is going to do.
     */
    String getDescription();
    
    /**
     * @return true if the template is savable (you can save the Gendoc template to modify it).
     */
    boolean isSavable();
}
